<h1 style="text-align: center; color: purple;" markdown="1">Econ220 Python Lab: Numpy exercises</h1>
<h2 style="text-align: center; color: #012169" markdown="1">Handout #3 </h2>

<p style="font-family: Calibri; text-align: left; color: darkgrey" markdown="2"></p>

By this time with your Datacamp practice you should be familiar with the numpy package. 


Let's refresh your mind about what numpy is and does and then let's get your hands active with some numpy exercises. 

* NumPy is the fundamental package for scientific computing in Python.

* It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), 
* An assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more. (Taken from [here](https://numpy.org/doc/stable/user/whatisnumpy.html))



# Package set up 

In [1]:
import numpy as np

* Create a null vector of size 10 

In [2]:
z1 = np.zeros(10)
print(z1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
# Autograder cell -do not delete it

* Create a null vector of size 10 but fourth value which is 1

In [3]:
z2 = np.zeros(10)
z2[3]=1
print(z2)

[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


In [ ]:
# Autograder cell -do not delete it

* Create a vector with values ranging from 10 to 49

In [4]:
z3 = np.arange(10,50)
print(z3)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
# Autograder cell -do not delete it

* Reverse a vector of numbers between 0 to 50 (first element becomes last)

In [5]:
z4 = np.arange(51)
z4 = z4[::-1]
print(z4)

[50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27
 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3
  2  1  0]


In [ ]:
# Autograder cell -do not delete it

* Find indices of non-zero elements from [3,2,1,0,0,5,4,6,0,10]

In [7]:
z5 = np.array([3,2,1,0,0,5,4,6,0,10])
print(np.nonzero(z5))

(array([0, 1, 2, 5, 6, 7, 9]),)


In [ ]:
# Autograder cell -do not delete it

* Create a random vector of size 30, sort it and find the average value

In [10]:
z6 = np.random.random(30)
print("Original Array:")
print(z6)
z6.sort()
print("Sorted Array:")
print(z6)
print("Mean array:")
z6.mean()


Original Array:
[0.00389577 0.76522031 0.67361343 0.81619389 0.51645395 0.17681835
 0.28095718 0.74864429 0.2824849  0.25463369 0.12148299 0.75316745
 0.09660161 0.88652444 0.18455106 0.01837538 0.26211258 0.56195722
 0.10636825 0.55207018 0.07766402 0.11067945 0.63790565 0.53505382
 0.23407573 0.55876325 0.41167198 0.06886397 0.20468167 0.71200657]
Sorted Array:
[0.00389577 0.01837538 0.06886397 0.07766402 0.09660161 0.10636825
 0.11067945 0.12148299 0.17681835 0.18455106 0.20468167 0.23407573
 0.25463369 0.26211258 0.28095718 0.2824849  0.41167198 0.51645395
 0.53505382 0.55207018 0.55876325 0.56195722 0.63790565 0.67361343
 0.71200657 0.74864429 0.75316745 0.76522031 0.81619389 0.88652444]
Mean array:


0.38711643365060283

* Given a 1D array (or vector) of 10 elements from 0-10, negate all elements which are between 4 and 8, in place. 

In [12]:
z7 = np.arange(10)
z7[(2<z7)&(z7<=8)]*=-1
print(z7)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9]


In [ ]:
# Autograder cell -do not delete it


<h1 style="text-align: center; color: purple;" markdown="1">Econ220 Python Lab: Numpy Arrays and Pandas DataFrames</h1>
<h2 style="text-align: center; color: #012169" markdown="1">Handout #4 </h2>

### Table of Contents
* [Understanding Data Structures in Python; The Pandas Package](#anchor1)
    * [The Package Set Up](#anchor2)
* [Two Useful Functions Numpy package](#anchor3)
* [Practice](#anchor4) 
* [Create a Dataframe Based on the Following Table ](#anchor5)
* [Using loc and .iloc on a data frame](#anchor6)



## Understanding Data Structures in Python; The Pandas Package <a class="anchor" id="anchor1"></a>


By now you know some basics of Python objects and the Numpy Package. In this handout you will learn about the most important structure in data analysis. **The dataframe.** In statistics, and later in econometrics, you will be working with data sets. These are comprised of observations and the variables asociated with them. The package **Pandas** allows you to manipulate data in Python. 

> **A dataframe in Python is a two-dimensional, labeled data structure with columns that can be of different types (numerical, characters, boolean), rows that indicate  observations/events, and takes the form of a rectangular grid, a structure that presents data in rows and columns similar to a spreadsheet. The columns are called variables, they are basically vectors, and the rows are called observations, like in a regular dataset.**


> **In pandas a dataframe is a collection of numpy arrays or a dictionary**

Let's learn a few new functions and put in practice what we know about dataframes and objects in Python.

#### The Package Set Up <a class="anchor" id="anchor2"></a>

In [13]:
# import the packages that you need in this case numpy and pandas
import numpy as np 
import pandas as pd 

## Two Useful Functions Numpy functions <a class = "anchor" id = "anchor3" ></a>


**To reapeat a number many times**

`np.repeat(a, repeats, axis=None)`

Where "a" is the object that you need to repeat, the next argument "repeats" gives the non-negative number of times the object a should be repated

**To create a vector of evenly space numbers within a range**

`np.arange(start, stop, step)`

Where start & stop represent the interval including start and excluding stop (this means that the number in place of stop is not included in the interval). 
Step represents the space between each number.


## In Class Exercise <a class="anchor" id="anchor4"></a>





* Create a vector of length 10 that repeats the number 5, name this vector x  
* Create a vector with all the numbers from 2 to 20 in incremeants of 2, name this vector y
* Print out the two vectors using the print( ) function
* Using Pandas, add the two vectors to a dataframe with columns "x" and "y"

> See how the **index starts at 0** in the data frame, that is how indexes are in Python this is **important to remember**

In [15]:
x=np.repeat(5,10,axis=None)
y=np.arange(2,21,2)
print(x)
print(y)
dataset = pd.DataFrame({"x":x,"y":y}, columns=["x","y"])
dataset

[5 5 5 5 5 5 5 5 5 5]
[ 2  4  6  8 10 12 14 16 18 20]


x   y
0  5   2
1  5   4
2  5   6
3  5   8
4  5  10
5  5  12
6  5  14
7  5  16
8  5  18
9  5  20

In [ ]:
# Autograder cell -do not delete it

## Create a Dataframe Based on the Following Table <a class = "anchor" id = "anchor5" ></a>


See the table below. It contains the information of the score that students obtained when two different reinforcement methods were used. 

|Male  |	| Female | |
| ------ | ------- | ------ | ------ |
| Electric Shock | Being Nice | Electric Shock | Being Nice |
|15 | 10 | 6 | 12|
|14 | 9 |	7 |	10|
|29 | 8 |	5 |	7|
|13 | 8 | 4	| 8|
|13 | 7 | 8	| 13|

Use the information of this table to create a dataframe in Python that has the adequate structure. Observations in the rows and variables in the columns. 

Use the function `np.repeat( )` when necessary.

Let's think about the steps to make this data into a data frame. 

* We have 3 attributes in the data set: 
* Sex (where M:= male; F:= female), 
* Reinforcement method (where ES:= electric shock; BN:= being nice), 
* and performance/score (positive integer values). 
* We need one vector per attribute 

In [21]:
sex = np.array(["M","F"])
# Ten Males and Ten Females
t=np.array([10,10])
# Method Type
me = np.array(["ES","BN","ES","BN"])
# Create the Vector for 5 Methods
t1 = np.repeat(5,4)
sex_vector = np.repeat(sex, t)
me_vector = np.repeat(me, t1)
# Score Vector
score = np.array([15,14,29,13,13,10,9,8,8,7,6,7,5,4,8,12,10,7,8,13])
print(sex_vector)

['M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'F' 'F' 'F' 'F' 'F' 'F' 'F' 'F'
 'F' 'F']


In [ ]:
# Autograder cell -do not delete it

In [ ]:
# Autograder cell -do not delete it

Now, having sucessfully inputted these three vectors into Python, we can compile our column vectors into a data frame and also save it as a CSV file. 

In [26]:
df_reinforcement = pd.DataFrame({"sex":sex_vector,"method":me_vector,"score":score},
                                columns = ["sex","method","score"])
# Save this data set to csv 
df_reinforcement.to_csv("Reinforcementdata.csv")

In [ ]:
# Autograder cell -do not delete it

## Using `.loc` and `.iloc` on a data frame <a class = "anchor" id = "anchor6" ></a>

When isnpecting a dataframe you always need to work with its dimensions, observations and variables or rows and columns. 
You can use the methods `.loc` and `.iloc` to inspect or do any data selection you want on your data frame. 
>`.loc` is label-based, which means that you have to specify rows and columns based on their row and column labels or names. 

>`iloc` is integer position based (from 0 to length-1 of the axis), in which case you specify rows and columns by their integer index or position.

**Data slicing:** Remember that in python index always start with zero and `[start(inclusive) : end(exclusive)]` so for example, if you slice a Numpy array (vector) that has 10 elements like this `vector[2:6]` this will take the element 3 to element 5 of the array. 

In [27]:
# Use iloc to view(reinforcement_df first 10 rows)
# View(reinforcement_df first 10 rows)
# .style will print the first 10 rows in a nice looking table
df_reinforcement.iloc[:10,].style

In [29]:
# Use loc to view reinforcement_df last 10 rows and only sex and score columns 
# View(reinforcement_df first 10 rows)
# .style method will print this selection rows in a nice looking table
df_reinforcement.loc[9:19,("sex","score")]



sex  score
9    M      7
10   F      6
11   F      7
12   F      5
13   F      4
14   F      8
15   F     12
16   F     10
17   F      7
18   F      8
19   F     13

In this case there is no difference in the rows because the index labels are numbers so they refer to the positions of the rows. But for the columns we refer to the labels instead of the positions.  

<hr />
<style>
div.gray { background-color:#dbdbdb; border-radius: 5px; padding: 20px;}
</style>
<div class = "gray">

<b>Packages used in this document</b>

Numpy
    
Pandas   

</div>


&nbsp;
<hr />
<p style="font-family:palatino; text-align: center;font-size: 15px">ECON220 Python Programming Laboratory</a></p>
<p style="font-family:palatino; text-align: center;font-size: 15px">Professor <em> Paloma Lopez de mesa Moyano</em></a></p>
<p style="font-family:palatino; text-align: center;font-size: 15px"><span style="color: #6666FF;"><em>paloma.moyano@emory.edu</em></span></p>

<p style="font-family:palatino; text-align: center;font-size: 15px">Department of Economics</a></p>
<p style="font-family:palatino; text-align: center; color: #012169;font-size: 15px">Emory University</a></p>

&nbsp;


In [32]:
#!jupyter nbconvert --to html namefile.ipynb

SyntaxError: invalid syntax (1073393977.py, line 1)