# Today's Lecture: Numpy Arrays & Pandas DataFrames

## 1. Numpy arrays

In [2]:
import numpy as np 

In [6]:
vector = np.array([1,2,3])
vector

array([1, 2, 3])

(a) Creating a vector of zeros

In [13]:
v1 = np.zeros(5)
#print(v1)

V = np.zeros((5,5))
#print(V)
print ("Vector v1 is equal to: ", v1, "\n Matrix V is : \n", V)

Vector v1 is equal to:  [0. 0. 0. 0. 0.] 
 Matrix V is : 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


(b) Creating a vector of ones

In [15]:
v2 = np.ones(4)
v2

array([1., 1., 1., 1.])

(c) Creating a vector of sequencial numbers 

In [22]:
v3 = np.array([1,2,3,4,5,6,7,8,9,10])
v3

v4 = np.arange(1,51)
print("v4:",v4)

v4: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]


In [23]:
v5 = np.arange(0,21, 2)
v5

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

(d) Create a vector a=(3, 0, 2, 1.7, 0, 0, 5). Then set b equal to the indices of the non-zero elements of a.

In [25]:
a = np.array([3,0,2,1.7,0,0,5])
b = np.nonzero(a)
print("Vector B of the indices of the non-zero elements of a: ", b)

Vector B of the indices of the non-zero elements of a:  (array([0, 2, 3, 6]),)


In [28]:
np.random.shuffle(a)
a

array([2. , 3. , 0. , 0. , 0. , 1.7, 5. ])

(e) Create a random vector with elements from 0 to 1 of dimension 5.

In [31]:
dim = 5
np.random.rand(dim)

array([0.34863462, 0.5111948 , 0.97567208, 0.86424164, 0.2579321 ])

## 2. Pandas DataFrames
### Data Info

In [34]:
import pandas as pd
path = 'https://www.alexandramanta.info/media/econ220_labs/'
data = pd.read_csv(path + 'BirthdataNC.csv')

(a) `.head()` , [documentation and examples link](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.head.html), `print()`, `.tail()` [documentation and examples link](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.tail.html), `.style` [documentation and examples link](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.style.html), `.to_markdown` [documentation and examples link](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_markdown.html)

In [38]:
data.head(2)

fage  mage       mature  weeks     premie  visits  marital  gained  weight  \
0   NaN    13  younger mom   39.0  full term    10.0  married    38.0    7.63   
1   NaN    14  younger mom   42.0  full term    15.0  married    20.0    7.88   

  lowbirthweight gender      habit   whitemom  
0        not low   male  nonsmoker  not white  
1        not low   male  nonsmoker  not white

In [39]:
print(data)

     fage  mage       mature  weeks     premie  visits      marital  gained  \
0     NaN    13  younger mom   39.0  full term    10.0      married    38.0   
1     NaN    14  younger mom   42.0  full term    15.0      married    20.0   
2    19.0    15  younger mom   37.0  full term    11.0      married    38.0   
3    21.0    15  younger mom   41.0  full term     6.0      married    34.0   
4     NaN    15  younger mom   39.0  full term     9.0      married    27.0   
..    ...   ...          ...    ...        ...     ...          ...     ...   
995  47.0    42   mature mom   40.0  full term    10.0  not married    26.0   
996  34.0    42   mature mom   38.0  full term    18.0  not married    20.0   
997  39.0    45   mature mom   40.0  full term    15.0  not married    32.0   
998  55.0    46   mature mom   31.0     premie     8.0  not married    25.0   
999  45.0    50   mature mom   39.0  full term    14.0  not married    23.0   

     weight lowbirthweight  gender      habit   whi

In [42]:
data.tail(2)

fage  mage      mature  weeks     premie  visits      marital  gained  \
998  55.0    46  mature mom   31.0     premie     8.0  not married    25.0   
999  45.0    50  mature mom   39.0  full term    14.0  not married    23.0   

     weight lowbirthweight  gender      habit   whitemom  
998    4.56            low  female  nonsmoker  not white  
999    7.13        not low  female  nonsmoker      white

In [43]:
data.to_markdown

<bound method DataFrame.to_markdown of      fage  mage       mature  weeks     premie  visits      marital  gained  \
0     NaN    13  younger mom   39.0  full term    10.0      married    38.0   
1     NaN    14  younger mom   42.0  full term    15.0      married    20.0   
2    19.0    15  younger mom   37.0  full term    11.0      married    38.0   
3    21.0    15  younger mom   41.0  full term     6.0      married    34.0   
4     NaN    15  younger mom   39.0  full term     9.0      married    27.0   
..    ...   ...          ...    ...        ...     ...          ...     ...   
995  47.0    42   mature mom   40.0  full term    10.0  not married    26.0   
996  34.0    42   mature mom   38.0  full term    18.0  not married    20.0   
997  39.0    45   mature mom   40.0  full term    15.0  not married    32.0   
998  55.0    46   mature mom   31.0     premie     8.0  not married    25.0   
999  45.0    50   mature mom   39.0  full term    14.0  not married    23.0   

     weight 

(b) `.info()` , [documentation and examples link](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.info.html)

In [44]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   fage            829 non-null    float64
 1   mage            1000 non-null   int64  
 2   mature          1000 non-null   object 
 3   weeks           998 non-null    float64
 4   premie          998 non-null    object 
 5   visits          991 non-null    float64
 6   marital         999 non-null    object 
 7   gained          973 non-null    float64
 8   weight          1000 non-null   float64
 9   lowbirthweight  1000 non-null   object 
 10  gender          1000 non-null   object 
 11  habit           999 non-null    object 
 12  whitemom        998 non-null    object 
dtypes: float64(5), int64(1), object(7)
memory usage: 101.7+ KB


(c) `.iat()` [documentation and examples link](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.iat.html)

In [46]:
data.iat[0,1]

13

(d) `.at()`, [documentation and examples link](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.at.html)

In [48]:
data.at[0,"visits"]

10.0

(e) `.iloc[ ]` , [documentation and examples link](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.iloc.html)

In [47]:
data.iloc[0,:]

fage                      NaN
mage                       13
mature            younger mom
weeks                    39.0
premie              full term
visits                   10.0
marital               married
gained                   38.0
weight                   7.63
lowbirthweight        not low
gender                   male
habit               nonsmoker
whitemom            not white
Name: 0, dtype: object

(f) `.loc[ ]` , [documentation and examples link](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.loc.html)

In [50]:
data.loc[0,["visits", "marital"]]

visits        10.0
marital    married
Name: 0, dtype: object

(g) `.size` , [documentation and examples link](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.size.html)

(h) `.shape` , [documentation and examples link](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.shape.html)

### Data Statistics

(a) `.mean()` , [documentation and examples link](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.mean.html)

(b) `.median()` , [documentation and examples link](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.median.html)

(c) `.min()` [documentation and examples link](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.min.html)

(d) `.max()` , [documentation and examples link](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.max.html)

(e)  `.describe()` , [documentation and examples link](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.describe.html)